name = "CardiovascularModels"
uuid = "77ddac30-6b02-4ad2-8af6-53f96db8cb6d"
authors = ["Johannes Enevoldsen <johannes.ne@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
ModelingToolkit = "8"
OrdinaryDiffEq = "6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
